<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <Nullable>enable</Nullable>
    <Platforms>x64</Platforms>
    <RootNamespace>ImageGlass.Tests</RootNamespace>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <ProjectReference Include="..\ImageGlass.Lib\ImageGlass.Lib.csproj" />
  </ItemGroup>
</Project>