<#
.SYNOPSIS
    Test driver for ImageGlass shared-zoom feature.

.PARAMETER ExePath
    Full path to ImageGlass.exe.

.PARAMETER TestImagesDir
    Directory containing the 4 test PNG images generated by SharedZoomTestGen.
    Defaults to c:\Users\Leonardo\001\00__DEV\ImageGlass-Krita\KRA\test_shared_zoom\
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string] $ExePath,

    [string] $TestImagesDir = 'c:\Users\Leonardo\001\00__DEV\ImageGlass-Krita\KRA\test_shared_zoom\'
)

# ---------------------------------------------------------------------------
# Helper: send a command to the diag pipe, return response string
# ---------------------------------------------------------------------------
function Send-DiagCmd {
    param([string] $Cmd)
    $pipeName = 'imageglass_diag'
    $maxAttempts = 5
    for ($attempt = 1; $attempt -le $maxAttempts; $attempt++) {
        try {
            $pipe = [System.IO.Pipes.NamedPipeClientStream]::new('.', $pipeName,
                [System.IO.Pipes.PipeDirection]::InOut,
                [System.IO.Pipes.PipeOptions]::None)
            $pipe.Connect(3000)

            $bytes = [System.Text.Encoding]::UTF8.GetBytes("$Cmd`n")
            $pipe.Write($bytes, 0, $bytes.Length)
            $pipe.Flush()

            $buffer = [byte[]]::new(8192)
            $read = $pipe.Read($buffer, 0, $buffer.Length)
            $pipe.Dispose()

            if ($read -gt 0) {
                return [System.Text.Encoding]::UTF8.GetString($buffer, 0, $read).Trim()
            }
        }
        catch {
            if ($attempt -eq $maxAttempts) { throw }
            Start-Sleep -Milliseconds 200
        }
    }
}

# Helper: QUERY returns parsed JSON object
function Query-DiagPipe {
    $json = Send-DiagCmd 'QUERY'
    return ($json | ConvertFrom-Json)
}

# Helper: wait until expected photo is fully loaded in viewer
function Wait-PhotoLoaded {
    param([string] $ExpectedFileName, [int] $TimeoutMs = 4000)
    $sw = [System.Diagnostics.Stopwatch]::StartNew()
    while ($sw.ElapsedMilliseconds -lt $TimeoutMs) {
        $state = Query-DiagPipe
        if ($state.FilePath -and (Split-Path $state.FilePath -Leaf) -eq $ExpectedFileName) {
            # Extra small pause for layout stabilization
            Start-Sleep -Milliseconds 100
            return (Query-DiagPipe)
        }
        Start-Sleep -Milliseconds 150
    }
    return (Query-DiagPipe)
}

# Helper: set zoom ratio (multiple of ScaleToFit)
function Set-Zoom {
    param([double] $Ratio)
    return (Send-DiagCmd "SET_ZOOM $Ratio")
}

# Helper: set pan position (0..1 fractions)
function Set-Pan {
    param([double] $NormX, [double] $NormY)
    return (Send-DiagCmd "SET_PAN $NormX $NormY")
}

# Helper: navigate image list by delta
function Navigate {
    param([int] $Delta = 1, [int] $WaitMs = 1000)
    Send-DiagCmd "NAVIGATE $Delta" | Out-Null
    Start-Sleep -Milliseconds $WaitMs
}

# ---------------------------------------------------------------------------
# Helper: print PASS / FAIL
# ---------------------------------------------------------------------------
$script:Results = [System.Collections.Generic.List[PSCustomObject]]::new()

function Assert-Test {
    param(
        [string] $TestName,
        [bool]   $Condition,
        [string] $Details = ''
    )
    if ($Condition) {
        Write-Host "  [PASS] $TestName" -ForegroundColor Green
        $script:Results.Add([PSCustomObject]@{ Test = $TestName; Result = 'PASS'; Details = '' })
    }
    else {
        Write-Host "  [FAIL] $TestName" -ForegroundColor Red
        if ($Details) { Write-Host "         $Details" -ForegroundColor Yellow }
        $script:Results.Add([PSCustomObject]@{ Test = $TestName; Result = 'FAIL'; Details = $Details })
    }
}

# ---------------------------------------------------------------------------
# Launch ImageGlass
# ---------------------------------------------------------------------------
Write-Host 'Cleaning up any running ImageGlass instances...'
Get-Process ImageGlass -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
Start-Sleep -Milliseconds 500

$firstImage = Join-Path $TestImagesDir 'A_large_landscape.png'
$argList = "--no-quick-setup --diag -p:EnableSharedZoom=true `"$firstImage`""
Write-Host "Launching ImageGlass: $ExePath $argList"
$proc = Start-Process -FilePath $ExePath -ArgumentList $argList -PassThru

Write-Host 'Waiting 3 s for startup...'
Start-Sleep -Seconds 3

# Store the T2 zoom ratio for the round-trip test (T4)
$script:T2ZoomRatio = $null

function Get-ViewportCenterFrac {
    param($state)
    if (-not $state -or $state.BitmapWidth -eq 0 -or $state.ZoomFactor -eq 0) {
        return [PSCustomObject]@{ FracX = 0.5; FracY = 0.5; R = 128; G = 128 }
    }
    $screenCenterX = $state.ViewportWidth / 2.0
    $screenCenterY = $state.ViewportHeight / 2.0

    $zFactor = $state.ZoomFactor / $state.Dpi

    $imgCenterX = $state.LogicalSrcX + (($screenCenterX - $state.DestX) / $zFactor)
    $imgCenterY = $state.LogicalSrcY + (($screenCenterY - $state.DestY) / $zFactor)

    $fracX = $imgCenterX / $state.BitmapWidth
    $fracY = $imgCenterY / $state.BitmapHeight

    return [PSCustomObject]@{
        FracX = $fracX
        FracY = $fracY
        R     = [Math]::Round($fracX * 255)
        G     = [Math]::Round($fracY * 255)
    }
}

function Zoom-ToPoint {
    param([double] $Ratio, [double] $ScreenX, [double] $ScreenY)
    return (Send-DiagCmd "ZOOM_TO_POINT $Ratio $ScreenX $ScreenY")
}

function Get-PointPixelColor {
    param($state, [double] $ScreenX, [double] $ScreenY)
    if (-not $state -or $state.BitmapWidth -eq 0 -or $state.ZoomFactor -eq 0) {
        return [PSCustomObject]@{ FracX = 0.5; FracY = 0.5; R = 128; G = 128 }
    }
    $zFactor = $state.ZoomFactor / $state.Dpi

    $imgX = $state.LogicalSrcX + (($ScreenX - $state.DestX) / $zFactor)
    $imgY = $state.LogicalSrcY + (($ScreenY - $state.DestY) / $zFactor)

    $fracX = $imgX / $state.BitmapWidth
    $fracY = $imgY / $state.BitmapHeight

    return [PSCustomObject]@{
        FracX = $fracX
        FracY = $fracY
        R     = [Math]::Round($fracX * 255)
        G     = [Math]::Round($fracY * 255)
    }
}

try {
    # -----------------------------------------------------------------------
    # T1 – Fit zoom baseline: both images start at ratio=1, pan=center
    # -----------------------------------------------------------------------
    Write-Host "`n--- T1: Fit zoom baseline ---"

    $stateA = Query-DiagPipe
    $centerA1 = Get-ViewportCenterFrac $stateA
    Write-Host "  [DBG] A: ZoomRatio=$($stateA.SharedZoomRatio) CenterFrac=($([Math]::Round($centerA1.FracX,3)), $([Math]::Round($centerA1.FracY,3))) R=$($centerA1.R) G=$($centerA1.G)"

    Navigate -Delta 1
    $stateB = Query-DiagPipe
    $centerB1 = Get-ViewportCenterFrac $stateB
    Write-Host "  [DBG] B: ZoomRatio=$($stateB.SharedZoomRatio) CenterFrac=($([Math]::Round($centerB1.FracX,3)), $([Math]::Round($centerB1.FracY,3))) R=$($centerB1.R) G=$($centerB1.G)"

    Assert-Test 'T1-ZoomRatio' `
        ([Math]::Abs($stateB.SharedZoomRatio - $stateA.SharedZoomRatio) -lt 0.01) `
        "A.ZoomRatio=$($stateA.SharedZoomRatio)  B.ZoomRatio=$($stateB.SharedZoomRatio)"

    Assert-Test 'T1-CenterColor-R' `
        ([Math]::Abs($centerB1.R - $centerA1.R) -le 2) `
        "A.R=$($centerA1.R)  B.R=$($centerB1.R)"

    Assert-Test 'T1-CenterColor-G' `
        ([Math]::Abs($centerB1.G - $centerA1.G) -le 2) `
        "A.G=$($centerA1.G)  B.G=$($centerB1.G)"

    # -----------------------------------------------------------------------
    # T2 – Top-left corner: zoom 2×, pan to (0,0), switch image
    # -----------------------------------------------------------------------
    Write-Host "`n--- T2: Top-left corner ---"

    Navigate -Delta -1    # back to A
    Set-Zoom -Ratio 2.0 | Out-Null
    Set-Pan -NormX 0.0 -NormY 0.0 | Out-Null
    Start-Sleep -Milliseconds 300

    $stateA2 = Query-DiagPipe
    $centerA2 = Get-ViewportCenterFrac $stateA2
    Write-Host "  [DBG] A after SET: ZoomRatio=$($stateA2.SharedZoomRatio) CenterFrac=($([Math]::Round($centerA2.FracX,3)), $([Math]::Round($centerA2.FracY,3))) R=$($centerA2.R) G=$($centerA2.G)"

    Navigate -Delta 1
    $stateB2 = Query-DiagPipe
    $centerB2 = Get-ViewportCenterFrac $stateB2
    Write-Host "  [DBG] B after NAV: ZoomRatio=$($stateB2.SharedZoomRatio) CenterFrac=($([Math]::Round($centerB2.FracX,3)), $([Math]::Round($centerB2.FracY,3))) R=$($centerB2.R) G=$($centerB2.G)"

    Assert-Test 'T2-ZoomRatioPreserved' `
        ([Math]::Abs($stateB2.SharedZoomRatio - $stateA2.SharedZoomRatio) -lt 0.01) `
        "A.ZoomRatio=$($stateA2.SharedZoomRatio)  B.ZoomRatio=$($stateB2.SharedZoomRatio)"

    Assert-Test 'T2-RenderedColorMatch-R' `
        ([Math]::Abs($centerB2.R - $centerA2.R) -le 2) `
        "A.R=$($centerA2.R)  B.R=$($centerB2.R)"

    Assert-Test 'T2-RenderedColorMatch-G' `
        ([Math]::Abs($centerB2.G - $centerA2.G) -le 2) `
        "A.G=$($centerA2.G)  B.G=$($centerB2.G)"

    # -----------------------------------------------------------------------
    # T3 – Bottom-right corner: zoom 2×, pan to (1,1), switch image
    # -----------------------------------------------------------------------
    Write-Host "`n--- T3: Bottom-right corner ---"

    Navigate -Delta -1    # back to A
    Set-Zoom -Ratio 2.0 | Out-Null
    Set-Pan -NormX 1.0 -NormY 1.0 | Out-Null
    Start-Sleep -Milliseconds 300

    $stateA3 = Query-DiagPipe
    $centerA3 = Get-ViewportCenterFrac $stateA3
    Write-Host "  [DBG] A after SET: ZoomRatio=$($stateA3.SharedZoomRatio) CenterFrac=($([Math]::Round($centerA3.FracX,3)), $([Math]::Round($centerA3.FracY,3))) R=$($centerA3.R) G=$($centerA3.G)"

    Navigate -Delta 1
    $stateB3 = Query-DiagPipe
    $centerB3 = Get-ViewportCenterFrac $stateB3
    Write-Host "  [DBG] B after NAV: ZoomRatio=$($stateB3.SharedZoomRatio) CenterFrac=($([Math]::Round($centerB3.FracX,3)), $([Math]::Round($centerB3.FracY,3))) R=$($centerB3.R) G=$($centerB3.G)"

    Assert-Test 'T3-RenderedColorMatch-R' `
        ([Math]::Abs($centerB3.R - $centerA3.R) -le 2) `
        "A.R=$($centerA3.R)  B.R=$($centerB3.R)"

    Assert-Test 'T3-RenderedColorMatch-G' `
        ([Math]::Abs($centerB3.G - $centerA3.G) -le 2) `
        "A.G=$($centerA3.G)  B.G=$($centerB3.G)"

    # -----------------------------------------------------------------------
    # T4 – Arbitrary pan (0.3, 0.7) across aspect ratio (landscape → portrait → landscape)
    # -----------------------------------------------------------------------
    Write-Host "`n--- T4: Arbitrary pan (0.3, 0.7) across aspect ratio ---"

    Navigate -Delta -1    # back to A
    Set-Zoom -Ratio 3.0 | Out-Null
    Set-Pan -NormX 0.3 -NormY 0.7 | Out-Null
    Start-Sleep -Milliseconds 300

    $stateA4 = Query-DiagPipe
    $centerA4 = Get-ViewportCenterFrac $stateA4
    Write-Host "  [DBG] A initial: ZoomRatio=$($stateA4.SharedZoomRatio) CenterFrac=($([Math]::Round($centerA4.FracX,3)), $([Math]::Round($centerA4.FracY,3))) R=$($centerA4.R) G=$($centerA4.G)"

    Navigate -Delta 1   # B
    Navigate -Delta 1   # C (portrait - pan X margin-clamped to prevent empty gap)
    $stateC4 = Query-DiagPipe
    $centerC4 = Get-ViewportCenterFrac $stateC4
    Write-Host "  [DBG] C portrait: ZoomRatio=$($stateC4.SharedZoomRatio) CenterFrac=($([Math]::Round($centerC4.FracX,3)), $([Math]::Round($centerC4.FracY,3))) R=$($centerC4.R) G=$($centerC4.G)"

    # Navigate back C → B → A
    Navigate -Delta -1  # B
    Navigate -Delta -1  # A
    $stateA4_return = Query-DiagPipe
    $centerA4_return = Get-ViewportCenterFrac $stateA4_return
    Write-Host "  [DBG] A returned: ZoomRatio=$($stateA4_return.SharedZoomRatio) CenterFrac=($([Math]::Round($centerA4_return.FracX,3)), $([Math]::Round($centerA4_return.FracY,3))) R=$($centerA4_return.R) G=$($centerA4_return.G)"

    Assert-Test 'T4-ZoomRatioPreserved' `
        ([Math]::Abs($stateA4_return.SharedZoomRatio - $stateA4.SharedZoomRatio) -lt 0.01) `
        "A.ZoomRatio=$($stateA4.SharedZoomRatio)  A_return.ZoomRatio=$($stateA4_return.SharedZoomRatio)"

    Assert-Test 'T4-RenderedColorMatch-R' `
        ([Math]::Abs($centerA4_return.R - $centerA4.R) -le 2) `
        "A.R=$($centerA4.R)  A_return.R=$($centerA4_return.R)"

    Assert-Test 'T4-RenderedColorMatch-G' `
        ([Math]::Abs($centerA4_return.G - $centerA4.G) -le 2) `
        "A.G=$($centerA4.G)  A_return.G=$($centerA4_return.G)"

    # -----------------------------------------------------------------------
    # T5 – Round-trip A→B→C→D→A zoom ratio preserved
    # -----------------------------------------------------------------------
    Write-Host "`n--- T5: Round-trip A→B→C→D→A ---"

    # navigate back to A (currently on C, two lefts)
    Navigate -Delta -1; Navigate -Delta -1

    Set-Zoom -Ratio 2.0 | Out-Null
    $ratioBeforeTrip = (Query-DiagPipe).SharedZoomRatio

    Navigate -Delta 1   # B
    Navigate -Delta 1   # C
    Navigate -Delta 1   # D
    Navigate -Delta 1   # A (wraps)

    $stateRT = Query-DiagPipe
    Write-Host "  [DBG] Round-trip: before=$ratioBeforeTrip  after=$($stateRT.SharedZoomRatio)"

    Assert-Test 'T5-RoundTripZoomRatio' `
        ([Math]::Abs($stateRT.SharedZoomRatio - $ratioBeforeTrip) -lt 0.01) `
        "expected=$ratioBeforeTrip  actual=$($stateRT.SharedZoomRatio)"

    # -----------------------------------------------------------------------
    # T6 – Arbitrary cursor zoom-to-point (200, 150) homology A → B
    # -----------------------------------------------------------------------
    Write-Host "`n--- T6: Zoom to cursor point (200, 150) preserved A → B ---"

    Navigate -Delta -1; Navigate -Delta -1; Navigate -Delta -1 # back to A
    $stateA6_init = Wait-PhotoLoaded 'A_large_landscape.png'
    Zoom-ToPoint -Ratio 2.5 -ScreenX 200 -ScreenY 150 | Out-Null
    Start-Sleep -Milliseconds 400

    $stateA6 = Query-DiagPipe
    $ptA6 = Get-PointPixelColor $stateA6 200 150
    Write-Host "  [DBG] A at (200,150): Frac=($([Math]::Round($ptA6.FracX,3)), $([Math]::Round($ptA6.FracY,3))) R=$($ptA6.R) G=$($ptA6.G)"

    Navigate -Delta 1  # B
    $stateB6 = Wait-PhotoLoaded 'B_small_landscape.png'
    $ptB6 = Get-PointPixelColor $stateB6 200 150
    Write-Host "  [DBG] B at (200,150): Frac=($([Math]::Round($ptB6.FracX,3)), $([Math]::Round($ptB6.FracY,3))) R=$($ptB6.R) G=$($ptB6.G)"

    Assert-Test 'T6-CursorColorMatch-R' `
        ([Math]::Abs($ptB6.R - $ptA6.R) -le 2) `
        "A.R=$($ptA6.R)  B.R=$($ptB6.R)"

    Assert-Test 'T6-CursorColorMatch-G' `
        ([Math]::Abs($ptB6.G - $ptA6.G) -le 2) `
        "A.G=$($ptA6.G)  B.G=$($ptB6.G)"
}
finally {
    if ($proc -and -not $proc.HasExited) {
        $proc.CloseMainWindow() | Out-Null
        $proc.WaitForExit(3000) | Out-Null
        if (-not $proc.HasExited) { Stop-Process -Id $proc.Id -Force }
    }
}

# ---------------------------------------------------------------------------
# Summary table
# ---------------------------------------------------------------------------
Write-Host "`n======= SUMMARY ======="
$script:Results | Format-Table -AutoSize

$failed = $script:Results | Where-Object { $_.Result -eq 'FAIL' }
if ($failed) {
    Write-Host "Result: FAILED ($($failed.Count) test(s) failed)" -ForegroundColor Red
    exit 1
}
else {
    Write-Host 'Result: ALL PASSED' -ForegroundColor Green
    exit 0
}
