<#
.SYNOPSIS
    Test driver for ImageGlass shared-zoom feature.

.PARAMETER ExePath
    Full path to ImageGlass.exe.

.PARAMETER TestImagesDir
    Directory containing the 4 test PNG images generated by SharedZoomTestGen.
    Defaults to c:\Users\Leonardo\001\00__DEV\ImageGlass-Krita\KRA\test_shared_zoom\
#>
[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [string] $ExePath,

    [string] $TestImagesDir = 'c:\Users\Leonardo\001\00__DEV\ImageGlass-Krita\KRA\test_shared_zoom\'
)

# ---------------------------------------------------------------------------
# Helper: send a command to the diag pipe, return response string
# ---------------------------------------------------------------------------
function Send-DiagCmd {
    param([string] $Cmd)
    $pipeName = 'imageglass_diag'
    $maxAttempts = 5
    for ($attempt = 1; $attempt -le $maxAttempts; $attempt++) {
        try {
            $pipe = [System.IO.Pipes.NamedPipeClientStream]::new('.', $pipeName,
                [System.IO.Pipes.PipeDirection]::InOut,
                [System.IO.Pipes.PipeOptions]::None)
            $pipe.Connect(3000)

            $bytes = [System.Text.Encoding]::UTF8.GetBytes("$Cmd`n")
            $pipe.Write($bytes, 0, $bytes.Length)
            $pipe.Flush()

            $buffer = [byte[]]::new(8192)
            $read = $pipe.Read($buffer, 0, $buffer.Length)
            $pipe.Dispose()

            if ($read -gt 0) {
                return [System.Text.Encoding]::UTF8.GetString($buffer, 0, $read).Trim()
            }
        }
        catch {
            if ($attempt -eq $maxAttempts) { throw }
            Start-Sleep -Milliseconds 200
        }
    }
}

# Helper: QUERY returns parsed JSON object
function Query-DiagPipe {
    $json = Send-DiagCmd 'QUERY'
    return ($json | ConvertFrom-Json)
}

# Helper: set zoom ratio (multiple of ScaleToFit)
function Set-Zoom {
    param([double] $Ratio)
    return (Send-DiagCmd "SET_ZOOM $Ratio")
}

# Helper: set pan position (0..1 fractions)
function Set-Pan {
    param([double] $NormX, [double] $NormY)
    return (Send-DiagCmd "SET_PAN $NormX $NormY")
}

# Helper: navigate image list by delta
function Navigate {
    param([int] $Delta = 1, [int] $WaitMs = 1000)
    Send-DiagCmd "NAVIGATE $Delta" | Out-Null
    Start-Sleep -Milliseconds $WaitMs
}

# ---------------------------------------------------------------------------
# Helper: print PASS / FAIL
# ---------------------------------------------------------------------------
$script:Results = [System.Collections.Generic.List[PSCustomObject]]::new()

function Assert-Test {
    param(
        [string] $TestName,
        [bool]   $Condition,
        [string] $Details = ''
    )
    if ($Condition) {
        Write-Host "  [PASS] $TestName" -ForegroundColor Green
        $script:Results.Add([PSCustomObject]@{ Test = $TestName; Result = 'PASS'; Details = '' })
    }
    else {
        Write-Host "  [FAIL] $TestName" -ForegroundColor Red
        if ($Details) { Write-Host "         $Details" -ForegroundColor Yellow }
        $script:Results.Add([PSCustomObject]@{ Test = $TestName; Result = 'FAIL'; Details = $Details })
    }
}

# ---------------------------------------------------------------------------
# Launch ImageGlass
# ---------------------------------------------------------------------------
Write-Host 'Cleaning up any running ImageGlass instances...'
Get-Process ImageGlass -ErrorAction SilentlyContinue | Stop-Process -Force -ErrorAction SilentlyContinue
Start-Sleep -Milliseconds 500

$firstImage = Join-Path $TestImagesDir 'A_large_landscape.png'
$argList = "--no-quick-setup --diag -p:EnableSharedZoom=true `"$firstImage`""
Write-Host "Launching ImageGlass: $ExePath $argList"
$proc = Start-Process -FilePath $ExePath -ArgumentList $argList -PassThru

Write-Host 'Waiting 3 s for startup...'
Start-Sleep -Seconds 3

# Store the T2 zoom ratio for the round-trip test (T4)
$script:T2ZoomRatio = $null

try {
    # -----------------------------------------------------------------------
    # T1 – Fit zoom baseline: both images start at ratio=1, pan=center
    # -----------------------------------------------------------------------
    Write-Host "`n--- T1: Fit zoom baseline ---"

    $stateA = Query-DiagPipe
    Write-Host "  [DBG] A: ZoomRatio=$($stateA.SharedZoomRatio) PanX=$($stateA.SharedZoomPanNormX) PanY=$($stateA.SharedZoomPanNormY)"

    Navigate -Delta 1
    $stateB = Query-DiagPipe
    Write-Host "  [DBG] B: ZoomRatio=$($stateB.SharedZoomRatio) PanX=$($stateB.SharedZoomPanNormX) PanY=$($stateB.SharedZoomPanNormY)"

    Assert-Test 'T1-ZoomRatio' `
        ([Math]::Abs($stateB.SharedZoomRatio - $stateA.SharedZoomRatio) -lt 0.01) `
        "A.ZoomRatio=$($stateA.SharedZoomRatio)  B.ZoomRatio=$($stateB.SharedZoomRatio)"

    Assert-Test 'T1-PanNormX' `
        ([Math]::Abs($stateB.SharedZoomPanNormX - $stateA.SharedZoomPanNormX) -lt 0.01) `
        "A.PanX=$($stateA.SharedZoomPanNormX)  B.PanX=$($stateB.SharedZoomPanNormX)"

    Assert-Test 'T1-PanNormY' `
        ([Math]::Abs($stateB.SharedZoomPanNormY - $stateA.SharedZoomPanNormY) -lt 0.01) `
        "A.PanY=$($stateA.SharedZoomPanNormY)  B.PanY=$($stateB.SharedZoomPanNormY)"

    # -----------------------------------------------------------------------
    # T2 – Top-left corner: zoom 2×, pan to (0,0), switch image
    # -----------------------------------------------------------------------
    Write-Host "`n--- T2: Top-left corner ---"

    Navigate -Delta -1    # back to A
    Set-Zoom -Ratio 2.0 | Out-Null
    Set-Pan -NormX 0.0 -NormY 0.0 | Out-Null
    Start-Sleep -Milliseconds 300

    $stateA2 = Query-DiagPipe
    $script:T2ZoomRatio = $stateA2.SharedZoomRatio
    Write-Host "  [DBG] A after SET: ZoomRatio=$($stateA2.SharedZoomRatio) PanX=$($stateA2.SharedZoomPanNormX) PanY=$($stateA2.SharedZoomPanNormY)"

    Navigate -Delta 1
    $stateB2 = Query-DiagPipe
    Write-Host "  [DBG] B after NAV: ZoomRatio=$($stateB2.SharedZoomRatio) PanX=$($stateB2.SharedZoomPanNormX) PanY=$($stateB2.SharedZoomPanNormY)"

    Assert-Test 'T2-ZoomRatioPreserved' `
        ([Math]::Abs($stateB2.SharedZoomRatio - $stateA2.SharedZoomRatio) -lt 0.01) `
        "A.ZoomRatio=$($stateA2.SharedZoomRatio)  B.ZoomRatio=$($stateB2.SharedZoomRatio)"

    Assert-Test 'T2-PanNormX-TopLeft' `
        ($stateB2.SharedZoomPanNormX -lt 0.05) `
        "B.PanNormX=$($stateB2.SharedZoomPanNormX)"

    Assert-Test 'T2-PanNormY-TopLeft' `
        ($stateB2.SharedZoomPanNormY -lt 0.05) `
        "B.PanNormY=$($stateB2.SharedZoomPanNormY)"

    # -----------------------------------------------------------------------
    # T3 – Bottom-right corner: zoom 2×, pan to (1,1), switch image
    # -----------------------------------------------------------------------
    Write-Host "`n--- T3: Bottom-right corner ---"

    Navigate -Delta -1    # back to A
    Set-Zoom -Ratio 2.0 | Out-Null
    Set-Pan -NormX 1.0 -NormY 1.0 | Out-Null
    Start-Sleep -Milliseconds 300

    $stateA3 = Query-DiagPipe
    Write-Host "  [DBG] A after SET: ZoomRatio=$($stateA3.SharedZoomRatio) PanX=$($stateA3.SharedZoomPanNormX) PanY=$($stateA3.SharedZoomPanNormY)"

    Navigate -Delta 1
    $stateB3 = Query-DiagPipe
    Write-Host "  [DBG] B after NAV: ZoomRatio=$($stateB3.SharedZoomRatio) PanX=$($stateB3.SharedZoomPanNormX) PanY=$($stateB3.SharedZoomPanNormY)"

    Assert-Test 'T3-PanNormX-BottomRight' `
        ($stateB3.SharedZoomPanNormX -gt 0.95) `
        "B.PanNormX=$($stateB3.SharedZoomPanNormX)"

    Assert-Test 'T3-PanNormY-BottomRight' `
        ($stateB3.SharedZoomPanNormY -gt 0.95) `
        "B.PanNormY=$($stateB3.SharedZoomPanNormY)"

    # -----------------------------------------------------------------------
    # T4 – Arbitrary interior pan: zoom 3×, pan to (0.3, 0.7), switch to portrait
    # -----------------------------------------------------------------------
    Write-Host "`n--- T4: Arbitrary pan (0.3, 0.7) across aspect ratio ---"

    Navigate -Delta -1    # back to A
    Set-Zoom -Ratio 3.0 | Out-Null
    Set-Pan -NormX 0.3 -NormY 0.7 | Out-Null
    Start-Sleep -Milliseconds 300

    $stateA4 = Query-DiagPipe
    Write-Host "  [DBG] A after SET: ZoomRatio=$($stateA4.SharedZoomRatio) PanX=$($stateA4.SharedZoomPanNormX) PanY=$($stateA4.SharedZoomPanNormY)"

    Navigate -Delta 1   # B
    Navigate -Delta 1   # C (portrait)
    $stateC4 = Query-DiagPipe
    Write-Host "  [DBG] C after NAV: ZoomRatio=$($stateC4.SharedZoomRatio) PanX=$($stateC4.SharedZoomPanNormX) PanY=$($stateC4.SharedZoomPanNormY)"

    Assert-Test 'T4-ZoomRatioPreserved' `
        ([Math]::Abs($stateC4.SharedZoomRatio - $stateA4.SharedZoomRatio) -lt 0.01) `
        "A.ZoomRatio=$($stateA4.SharedZoomRatio)  C.ZoomRatio=$($stateC4.SharedZoomRatio)"

    Assert-Test 'T4-PanX-0.3' `
        ([Math]::Abs($stateC4.SharedZoomPanNormX - 0.3) -lt 0.02) `
        "C.PanNormX=$($stateC4.SharedZoomPanNormX) (expected ~0.3)"

    Assert-Test 'T4-PanY-0.7' `
        ([Math]::Abs($stateC4.SharedZoomPanNormY - 0.7) -lt 0.02) `
        "C.PanNormY=$($stateC4.SharedZoomPanNormY) (expected ~0.7)"

    # -----------------------------------------------------------------------
    # T5 – Round-trip A→B→C→D→A zoom ratio preserved
    # -----------------------------------------------------------------------
    Write-Host "`n--- T5: Round-trip A→B→C→D→A ---"

    # navigate back to A (currently on C, two lefts)
    Navigate -Delta -1; Navigate -Delta -1

    Set-Zoom -Ratio 2.0 | Out-Null
    $ratioBeforeTrip = (Query-DiagPipe).SharedZoomRatio

    Navigate -Delta 1   # B
    Navigate -Delta 1   # C
    Navigate -Delta 1   # D
    Navigate -Delta 1   # A (wraps)

    $stateRT = Query-DiagPipe
    Write-Host "  [DBG] Round-trip: before=$ratioBeforeTrip  after=$($stateRT.SharedZoomRatio)"

    Assert-Test 'T5-RoundTripZoomRatio' `
        ([Math]::Abs($stateRT.SharedZoomRatio - $ratioBeforeTrip) -lt 0.01) `
        "expected=$ratioBeforeTrip  actual=$($stateRT.SharedZoomRatio)"
}
finally {
    if ($proc -and -not $proc.HasExited) {
        $proc.CloseMainWindow() | Out-Null
        $proc.WaitForExit(3000) | Out-Null
        if (-not $proc.HasExited) { Stop-Process -Id $proc.Id -Force }
    }
}

# ---------------------------------------------------------------------------
# Summary table
# ---------------------------------------------------------------------------
Write-Host "`n======= SUMMARY ======="
$script:Results | Format-Table -AutoSize

$failed = $script:Results | Where-Object { $_.Result -eq 'FAIL' }
if ($failed) {
    Write-Host "Result: FAILED ($($failed.Count) test(s) failed)" -ForegroundColor Red
    exit 1
}
else {
    Write-Host 'Result: ALL PASSED' -ForegroundColor Green
    exit 0
}
